#include <sy5/request.h>

static const char *request_item_names_array[] = {
    [CLIENT_REQUEST_LIST_TASKS] = "CLIENT_REQUEST_LIST_TASKS",
    [CLIENT_REQUEST_CREATE_TASK] = "CLIENT_REQUEST_CREATE_TASK",
    [CLIENT_REQUEST_REMOVE_TASK] = "CLIENT_REQUEST_REMOVE_TASK",
    [CLIENT_REQUEST_GET_TIMES_AND_EXITCODES] = "CLIENT_REQUEST_GET_TIMES_AND_EXITCODES",
    [CLIENT_REQUEST_GET_STDOUT] = "CLIENT_REQUEST_GET_STDOUT",
    [CLIENT_REQUEST_GET_STDERR] = "CLIENT_REQUEST_GET_STDERR",
    [CLIENT_REQUEST_TERMINATE] = "CLIENT_REQUEST_TERMINATE",
    
    [CLIENT_REQUEST_COUNT] = 0,
};

const char **request_item_names() {
    return request_item_names_array;
}